name: CI Angular app through Github Actions
on: 
 #push:
    #branches:
    #  - 'master'
    #branches-ignore:
    #  - "master"
    pull_request:
      branches:
        - 'master'
jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install npm packages
        run: npm ci

 #     - name: Run Lint
 #       run: npm run lint

      - name: Run unit test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build the application
        run: npm run build
      
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: app dist
          path: Application Build
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: Test coverage
          path: coverage
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3