name: Testing Github Actions and Workflow
on: 
 #push:
    #branches:
    #  - 'master'
    #branches-ignore:
    #  - "master"
    pull_request:
      branches:
        - 'master'
        - 'dev'
jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
        branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      -id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"