name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'main'  
jobs:
  printInput:
    runs-on: ubuntu-latest
    steps:
    - name: Print Branch Name 
      run: echo "Workflow will run with ${{ github.event.inputs.branch }} environment"

  stageCI:
    runs-on: ubuntu-latest
    needs: printInput
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
#        cache: 'npm'

    - name: Install npm packages
      run: npm ci

#     - name: Run Lint
#       run: npm run lint

    - name: Run unit test
      run: npm run test:ci

    # For Stage Build
    - name: Build the application for stage
      if: ${{ github.event.inputs.branch == 'staging' }}
      run: npm run build:stage

    # For Development Build
    - name: Build the application for development
      if: ${{ github.event.inputs.branch == 'development' }}
      run: npm run build:stage

    # For Default Build
    - name: Build the application for default
      if: ${{ github.event.inputs.branch == 'main' }}
      run: npm run build:stage    
    
    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: Application Build
        path: dist
    - name: Archive code coverage result
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: Application Test coverage
        path: coverage 